name: C/C++ CI with Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM and other dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y llvm lcov

    - name: Build and run tests
      run: |
        make
        make test

    - name: Generate coverage report
      if: success()
      run: |
        llvm-cov gcov --directory . --output-dir coverage --format=lcov

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage
