name: C/C++ CI with Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y lcov

    - name: Build project
      run: |
        make

    - name: Run unit tests and generate coverage info
      run: |
        make test
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/test/*' '*/Doctest.hpp' '*/tests.cpp' '*/Tela.cpp' '*/main.cpp' --output-file coverage.info
        lcov --list coverage.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
