name: C/C++ CI with Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gcov lcov

    - name: Build and run tests
      run: |
        make
        make test

    - name: Generate coverage report
      if: success()
      run: |
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info  # Exclude system headers
        lcov --list coverage.info  # Optional: display coverage summary on console

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.info
