name: C/C++ CI with Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: make
      run: |
        make
        make test
        
    - name: Generate a code coverage report
      uses: threeal/gcovr-action@v1.0.0
      with:
        xml-out: coverage.xml
        coveralls-send: true  # Optional: Send to Coveralls if needed
        github-token: ${{ secrets.GITHUB_TOKEN }}
        excludes: |
          include/Doctest.hpp
          src/tests.cpp
          src/Tela.cpp
          src/main.cpp

# Add more jobs or steps as necessary for your CI/CD pipeline
